from __future__ import annotations

import json
import re
from typing import Any

from sqlalchemy import select
from langchain_core.messages import HumanMessage

from app.agent.graph import build_graph
from app.data.service import DatasetService
from app.db.database import SessionLocal
from app.db.models import LLMModel
from app.llm.ollama import OllamaClient


class ChatService:

    def __init__(self):
        """Initialize the chat service and its dependencies."""

        self.ollama = OllamaClient()
        self.dataset_service = DatasetService()

    def get_model(self, model_name: str) -> LLMModel:
        """Return an active LLM model by its name.

        Args:
            model_name: Name of the model to retrieve.

        Returns:
            The active LLMModel instance.

        Raises:
            ValueError: If the model does not exist or is inactive.
        """

        db = SessionLocal()

        try:
            model = db.scalar(
                select(LLMModel).where(
                    LLMModel.name == model_name,
                    LLMModel.active.is_(True),
                )
            )

            if model is None:
                raise ValueError(
                    f"Model '{model_name}' is not found or inactive"
                )

            return model

        finally:
            db.close()

    def get_dataset_schema(
        self,
        dataset_id: int,
    ) -> dict[str, Any]:
        """Return the schema and metadata for a dataset.

        Args:
            dataset_id: ID of the dataset to inspect.

        Returns:
            A dictionary containing the dataset name, columns,
            column types, row count, and dataset ID.

        Raises:
            ValueError: If the dataset does not exist.
        """

        dataset = self.dataset_service.get_dataset(
            dataset_id
        )

        if dataset is None:
            raise ValueError(
                f"Dataset '{dataset_id}' not found"
            )

        connection = self.dataset_service.duckdb.connect(
            str(dataset_id)
        )

        try:
            columns = connection.execute(
                "DESCRIBE data"
            ).fetchall()

            return {
                "dataset_id": dataset_id,
                "name": dataset["name"],
                "columns": [
                    {
                        "name": column[0],
                        "type": column[1],
                    }
                    for column in columns
                ],
                "row_count": dataset["row_count"],
            }

        finally:
            connection.close()

    @staticmethod
    def clean_sql(
        sql: str,
    ) -> str:
        """Clean SQL generated by the language model.

        Removes markdown code fences, surrounding whitespace,
        and a trailing semicolon.

        Args:
            sql: Raw SQL string generated by the LLM.

        Returns:
            Cleaned SQL query.
        """

        sql = sql.strip()

        sql = re.sub(
            r"^```(?:sql)?\s*",
            "",
            sql,
            flags=re.IGNORECASE,
        )

        sql = re.sub(
            r"\s*```$",
            "",
            sql,
        )

        sql = sql.strip()

        sql = sql.rstrip(";").strip()

        return sql

    def validate_generated_sql(
        self,
        dataset_id: int,
        sql: str,
    ) -> str:
        """Validate and test an LLM-generated SQL query.

        The query is cleaned, checked to ensure it is a single
        SELECT statement, and executed against the dataset.

        Args:
            dataset_id: ID of the dataset against which SQL is tested.
            sql: SQL query generated by the LLM.

        Returns:
            The cleaned and validated SQL query.

        Raises:
            ValueError: If the SQL is empty, contains multiple
                statements, is not a SELECT query, or fails execution.
        """

        sql = self.clean_sql(sql)

        if not sql:
            raise ValueError(
                "Generated SQL is empty"
            )

        if ";" in sql:
            raise ValueError(
                "Only one SQL query is allowed"
            )

        normalized_sql = sql.lower().strip()

        if not normalized_sql.startswith("select"):
            raise ValueError(
                "Generated SQL must be a SELECT query"
            )

        connection = self.dataset_service.duckdb.connect(
            str(dataset_id)
        )

        try:
            connection.execute(sql)

        except Exception as exc:
            raise ValueError(
                f"Generated SQL execution failed: {exc}"
            ) from exc

        finally:
            connection.close()

        return sql

    def _build_sql_prompt(
        self,
        question: str,
        schema: dict[str, Any],
    ) -> str:
        """Build a prompt for generating SQL from a user question.

        Args:
            question: User's natural-language question.
            schema: Dataset schema containing column names and types.

        Returns:
            A formatted prompt instructing the LLM to generate
            a valid DuckDB SELECT query.
        """

        columns_text = "\n".join(
            f'- "{column["name"]}" ({column["type"]})'
            for column in schema["columns"]
        )

        return f"""
You are an expert SQL analyst.

Generate ONE DuckDB SQL query that answers the user's question.

Dataset table:
data

Columns:
{columns_text}

Rules:
- Return ONLY SQL.
- Do not use markdown.
- Do not use ```sql.
- Only SELECT queries are allowed.
- The table name is exactly "data".
- Use DuckDB SQL syntax.
- If an aggregation is required, calculate it in SQL.
- If a numeric column is stored as VARCHAR, use CAST when necessary.
- Respect the actual column types shown above.
- Do not invent columns.
- Do not invent tables.
- The schema is authoritative.
- Every column referenced in SQL MUST exist in the provided Columns list.
- Never use a column name that is not explicitly listed.
- Before generating SQL, mentally verify every referenced column against the schema.
- If the user asks for revenue, sales amount, turnover or total sales, do not invent a "sales" column.
- If quantity and price columns exist, revenue should normally be calculated as quantity * price.
- If quantity or price is VARCHAR, CAST it to a numeric type before arithmetic.

DATE RULES:
- If a column has type DATE, use DuckDB DATE syntax when appropriate.
- Example:
  date >= DATE '2026-01-11'
- If a column has type VARCHAR but contains date strings, CAST may be required.
- Example:
  CAST(date AS DATE) >= DATE '2026-01-11'

BOOLEAN RULES:
- If a column has type BOOLEAN, use TRUE or FALSE.
- Example:
  WHERE active = TRUE
  or:
  WHERE active

COLUMN NAMING RULES:
- Every calculated, aggregated, or expression-based column MUST have an explicit AS alias.
- Never return an unnamed expression in SELECT.
- Aliases must be short, meaningful, descriptive, and use English snake_case.

Examples:
    SUM(sales) AS total_sales
    AVG(price) AS average_price
    COUNT(*) AS row_count
    quantity * price AS revenue
    SUM(quantity * price) AS total_revenue
    MAX(price) AS max_price
    MIN(price) AS min_price

- Plain source columns do not require aliases.
- SELECT * is allowed when appropriate.
- DISTINCT plain source columns do not require aliases.

IMPORTANT:
Every expression in SELECT that is not a plain source column MUST have an AS alias.

The generated SQL is invalid if any calculated expression has no alias.

USER QUESTION:
{question}
""".strip()

    def _build_sql_repair_prompt(
        self,
        question: str,
        schema: dict[str, Any],
        sql: str,
        error: str,
    ) -> str:
        """Build a prompt for repairing failed SQL.

        Args:
            question: User's original natural-language question.
            schema: Dataset schema containing column names and types.
            sql: SQL query that failed.
            error: Error returned during SQL validation or execution.

        Returns:
            A formatted prompt instructing the LLM to correct
            the failed SQL query.
        """

        columns_text = "\n".join(
            f'- "{column["name"]}" ({column["type"]})'
            for column in schema["columns"]
        )

        return f"""
You are an expert DuckDB SQL debugger.

The previous SQL query failed validation or execution.

Your task is to FIX the SQL query.

USER QUESTION:
{question}

DATASET TABLE:
data

COLUMNS:
{columns_text}

ORIGINAL SQL:
{sql}

DUCKDB ERROR:
{error}

RULES:
- Return ONLY the corrected SQL.
- Do not use markdown.
- Do not use ```sql.
- Return exactly ONE SQL query.
- Only SELECT queries are allowed.
- The table name is exactly "data".
- Use valid DuckDB SQL syntax.
- Do not invent columns.
- Do not invent tables.
- Every referenced column MUST exist in the COLUMNS list.
- If DuckDB reports that a column does not exist, replace it with an actual column from the schema.
- If DuckDB reports a VARCHAR numeric-operation error, use CAST(... AS DOUBLE).
- For revenue calculations, if quantity and price columns exist, calculate quantity * price.
- Never invent a column such as sales, revenue, amount, total_sales, etc. unless it actually exists in the schema.
- Preserve the user's intended meaning.
- Respect the actual column types shown above.

DATE RULES:
- If a column has type DATE, compare it with DATE literals when appropriate.
- Example:
  date >= DATE '2026-01-11'
- If the actual column type is VARCHAR and it contains date strings,
  use CAST(date AS DATE) when a DATE comparison is required.
- Example:
  CAST(date AS DATE) >= DATE '2026-01-11'

BOOLEAN RULES:
- BOOLEAN columns can be compared with TRUE/FALSE.
- Example:
  active = TRUE
  or:
  WHERE active

COLUMN NAMING RULES:
- Every calculated, aggregated, or expression-based column MUST have an explicit AS alias.
- Never return an unnamed expression in SELECT.
- Use short, meaningful English snake_case aliases.

Examples:
    SUM(sales) AS total_sales
    AVG(price) AS average_price
    quantity * price AS revenue
    SUM(quantity * price) AS total_revenue

IMPORTANT BUSINESS EXAMPLE:

If the schema contains:
- quantity (VARCHAR)
- price (VARCHAR)

and the user asks:
"Calculate the total sales amount."

generate:

SELECT
    SUM(
        CAST(quantity AS DOUBLE)
        * CAST(price AS DOUBLE)
    ) AS total_revenue
FROM data

Do NOT generate:
SELECT SUM(sales) AS total_revenue FROM data

because "sales" does not exist in the schema.

IMPORTANT:
Fix the SQL based on the actual DuckDB error.
Do not merely repeat the original SQL.

Return ONLY the corrected SQL.
""".strip()

    def generate_sql(
        self,
        model_name: str,
        question: str,
        schema: dict[str, Any],
        dataset_id: int,
    ) -> str:
        """Generate and validate a SQL query for a user question.

        Args:
            model_name: Name of the LLM used for SQL generation.
            question: User's natural-language question.
            schema: Dataset schema used to guide SQL generation.
            dataset_id: ID of the dataset used for validation.

        Returns:
            A validated SQL SELECT query.

        Raises:
            ValueError: If the LLM returns invalid or empty SQL.
        """

        prompt = self._build_sql_prompt(
            question=question,
            schema=schema,
        )

        response = self.ollama.generate(
            model=model_name,
            prompt=prompt,
            temperature=0.0,
        )

        sql = response.get(
            "response",
            "",
        )

        sql = self.clean_sql(sql)

        if not sql:
            raise ValueError(
                "LLM returned an empty SQL query"
            )

        return self.validate_generated_sql(
            dataset_id=dataset_id,
            sql=sql,
        )

    def generate_sql_with_repair(
        self,
        model_name: str,
        question: str,
        schema: dict[str, Any],
        dataset_id: int,
        max_attempts: int = 3,
    ) -> str:
        """Generate SQL and retry with an automatic repair prompt.

        Args:
            model_name: Name of the LLM used for SQL generation.
            question: User's natural-language question.
            schema: Dataset schema used for SQL generation.
            dataset_id: ID of the dataset used for validation.
            max_attempts: Maximum number of SQL validation attempts.

        Returns:
            A validated SQL SELECT query.

        Raises:
            ValueError: If SQL generation fails after all attempts.
        """

        if max_attempts < 1:
            raise ValueError(
                "max_attempts must be at least 1"
            )

        prompt = self._build_sql_prompt(
            question=question,
            schema=schema,
        )

        response = self.ollama.generate(
            model=model_name,
            prompt=prompt,
            temperature=0.0,
        )

        sql = self.clean_sql(
            response.get("response", "")
        )

        if not sql:
            raise ValueError(
                "LLM returned an empty SQL query"
            )

        last_error: Exception | None = None

        for attempt in range(max_attempts):

            try:
                return self.validate_generated_sql(
                    dataset_id=dataset_id,
                    sql=sql,
                )

            except Exception as exc:
                last_error = exc

                if attempt == max_attempts - 1:
                    break

                repair_prompt = self._build_sql_repair_prompt(
                    question=question,
                    schema=schema,
                    sql=sql,
                    error=str(exc),
                )

                repair_response = self.ollama.generate(
                    model=model_name,
                    prompt=repair_prompt,
                    temperature=0.0,
                )

                sql = self.clean_sql(
                    repair_response.get(
                        "response",
                        "",
                    )
                )

                if not sql:
                    last_error = ValueError(
                        "LLM returned an empty SQL query during repair"
                    )
                    break

        raise ValueError(
            f"SQL generation failed after "
            f"{max_attempts} attempts: {last_error}"
        )

    def chat(
        self,
        model_name: str,
        question: str,
        dataset_id: int | None = None,
    ) -> dict[str, Any]:
        """Process a user question using the selected LLM and dataset.

        Without a dataset, the question is sent directly to the LLM.
        With a dataset, the LangGraph agent is used for data analysis.

        Args:
            model_name: Name of the LLM to use.
            question: User's natural-language question.
            dataset_id: Optional ID of the dataset to analyze.

        Returns:
            A dictionary containing the answer, model information,
            usage statistics, cost, and dataset/SQL information when
            a dataset is provided.

        Raises:
            ValueError: If the model or dataset does not exist or
                the agent does not return an answer.
        """

        model = self.get_model(
            model_name
        )

        if dataset_id is None:

            response = self.ollama.generate(
                model=model.name,
                prompt=question,
                temperature=0.2,
            )

            input_tokens = int(
                response.get(
                    "prompt_eval_count"
                ) or 0
            )

            output_tokens = int(
                response.get(
                    "eval_count"
                ) or 0
            )

            return {
                "answer": response.get(
                    "response",
                    "",
                ),
                "model": {
                    "id": model.id,
                    "name": model.name,
                    "display_name": model.display_name,
                },
                "usage": {
                    "input_tokens": input_tokens,
                    "output_tokens": output_tokens,
                    "total_tokens": (
                        input_tokens
                        + output_tokens
                    ),
                },
                "cost": self.calculate_cost(
                    model=model,
                    input_tokens=input_tokens,
                    output_tokens=output_tokens,
                ),
            }

        dataset = self.dataset_service.get_dataset(
            dataset_id
        )

        if dataset is None:
            raise ValueError(
                f"Dataset '{dataset_id}' not found"
            )

        graph = build_graph(
            model_name=model.name,
            dataset_id=dataset_id,
        )

        result = graph.invoke(
            {
                "messages": [
                    HumanMessage(
                        content=question
                    )
                ],
                "dataset_id": dataset_id,
                "question": question,
                "schema": {},
                "sample": [],
                "sql": "",
                "sql_error": None,
                "result": None,
                "answer": "",
                "input_tokens": 0,
                "output_tokens": 0,
            }
        )

        messages = result.get(
            "messages",
            []
        )

        answer = ""

        for message in reversed(messages):

            if message.__class__.__name__ == "AIMessage":

                content = getattr(
                    message,
                    "content",
                    "",
                )

                if content:
                    answer = content
                    break

        if not answer:
            raise ValueError(
                "Agent did not return an answer"
            )

        sql = None
        data = None
        used_columns = []

        for message in reversed(messages):

            if message.__class__.__name__ != "ToolMessage":
                continue

            tool_name = getattr(
                message,
                "name",
                "",
            )

            if tool_name != "execute_sql":
                continue

            content = getattr(
                message,
                "content",
                "",
            )

            if isinstance(content, dict):
                tool_result = content

            else:
                try:
                    tool_result = json.loads(
                        content
                    )

                except (
                    TypeError,
                    ValueError,
                ):
                    tool_result = None

            if isinstance(tool_result, dict):

                sql = tool_result.get(
                    "sql"
                )

                used_columns = tool_result.get(
                    "used_columns",
                    [],
                )

                data = {
                    "dataset_id": dataset_id,
                    "columns": tool_result.get(
                        "columns",
                        [],
                    ),
                    "rows": tool_result.get(
                        "rows",
                        [],
                    ),
                    "row_count": tool_result.get(
                        "row_count",
                        0,
                    ),
                }

            break

        input_tokens = 0
        output_tokens = 0

        for message in messages:

            usage_metadata = getattr(
                message,
                "usage_metadata",
                None,
            )

            if not usage_metadata:
                continue

            input_tokens += int(
                usage_metadata.get(
                    "input_tokens",
                    0,
                )
                or 0
            )

            output_tokens += int(
                usage_metadata.get(
                    "output_tokens",
                    0,
                )
                or 0
            )

        return {
            "answer": answer,
            "used_columns": used_columns,
            "model": {
                "id": model.id,
                "name": model.name,
                "display_name": model.display_name,
            },
            "dataset": {
                "id": dataset_id,
                "name": dataset["name"],
                "row_count": dataset["row_count"],
            },
            "sql": sql,
            "data": data,
            "usage": {
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "total_tokens": (
                    input_tokens
                    + output_tokens
                ),
            },
            "cost": self.calculate_cost(
                model=model,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
            ),
        }

    def _repair_executed_sql(
        self,
        model_name: str,
        question: str,
        schema: dict[str, Any],
        sql: str,
        error: str,
        max_attempts: int = 2,
    ) -> str:
        """Repair SQL after a runtime execution failure.

        Args:
            model_name: Name of the LLM used to repair the query.
            question: User's original question.
            schema: Dataset schema used to correct the query.
            sql: SQL query that failed during execution.
            error: Runtime SQL error message.
            max_attempts: Maximum number of repair attempts.

        Returns:
            A corrected and validated SQL query.

        Raises:
            ValueError: If the SQL cannot be repaired successfully.
        """

        current_sql = sql

        for attempt in range(max_attempts):

            repair_prompt = self._build_sql_repair_prompt(
                question=question,
                schema=schema,
                sql=current_sql,
                error=error,
            )

            response = self.ollama.generate(
                model=model_name,
                prompt=repair_prompt,
                temperature=0.0,
            )

            repaired_sql = self.clean_sql(
                response.get(
                    "response",
                    "",
                )
            )

            if not repaired_sql:
                raise ValueError(
                    "LLM returned an empty SQL query during runtime repair"
                )

            try:
                return self.validate_generated_sql(
                    dataset_id=schema["dataset_id"],
                    sql=repaired_sql,
                )

            except Exception as exc:

                current_sql = repaired_sql
                error = str(exc)

                if attempt == max_attempts - 1:
                    raise ValueError(
                        f"SQL repair failed: {error}"
                    ) from exc

        raise ValueError(
            "SQL repair failed"
        )

    @staticmethod
    def calculate_cost(
        model: LLMModel,
        input_tokens: int,
        output_tokens: int,
    ) -> float:
        """Calculate the cost of an LLM request.

        Args:
            model: LLM model containing input and output token prices.
            input_tokens: Number of input tokens used.
            output_tokens: Number of output tokens used.

        Returns:
            Total request cost rounded to eight decimal places.
        """

        input_cost = (
            input_tokens / 1_000_000
        ) * model.input_price_per_1m

        output_cost = (
            output_tokens / 1_000_000
        ) * model.output_price_per_1m

        return round(
            input_cost + output_cost,
            8,
        )

    async def chat_stream(
        self,
        model_name: str,
        question: str,
        dataset_id: int | None = None,
    ):
        """Stream an LLM response and dataset analysis events.

        Without a dataset, streams tokens directly from Ollama.
        With a dataset, streams events produced by the LangGraph
        data analysis agent.

        Args:
            model_name: Name of the LLM to use.
            question: User's natural-language question.
            dataset_id: Optional ID of the dataset to analyze.

        Yields:
            Dictionaries representing streamed tokens, metadata,
            completion information, usage statistics, and cost.

        Raises:
            ValueError: If the selected model or dataset does not exist.
        """

        model = self.get_model(
            model_name
        )

        if dataset_id is None:

            for chunk in self.ollama.generate_stream(
                model=model.name,
                prompt=question,
                temperature=0.2,
            ):
                if not chunk:
                    continue

                content = chunk.get(
                    "response",
                    "",
                )

                if content:
                    yield {
                        "type": "token",
                        "content": content,
                    }

                if chunk.get("done"):

                    input_tokens = int(
                        chunk.get(
                            "prompt_eval_count",
                            0,
                        )
                        or 0
                    )

                    output_tokens = int(
                        chunk.get(
                            "eval_count",
                            0,
                        )
                        or 0
                    )

                    yield {
                        "type": "done",
                        "usage": {
                            "input_tokens": input_tokens,
                            "output_tokens": output_tokens,
                            "total_tokens": (
                                input_tokens
                                + output_tokens
                            ),
                        },
                        "cost": self.calculate_cost(
                            model=model,
                            input_tokens=input_tokens,
                            output_tokens=output_tokens,
                        ),
                    }

            return

        dataset = self.dataset_service.get_dataset(
            dataset_id
        )

        if dataset is None:
            raise ValueError(
                f"Dataset '{dataset_id}' not found"
            )

        graph = build_graph(
            model_name=model.name,
            dataset_id=dataset_id,
        )

        initial_state = {
            "messages": [
                HumanMessage(
                    content=question
                )
            ],
            "dataset_id": dataset_id,
            "question": question,
            "schema": {},
            "sample": [],
            "sql": "",
            "sql_error": None,
            "result": None,
            "answer": "",
            "input_tokens": 0,
            "output_tokens": 0,
        }

        input_tokens = 0
        output_tokens = 0

        sql = None
        used_columns = []
        data = None

        metadata_sent = False

        async for event in graph.astream_events(
            initial_state,
            version="v2",
        ):

            event_type = event.get(
                "event"
            )
            
            if event_type == "on_chat_model_stream":

                chunk = event.get(
                    "data",
                    {},
                ).get(
                    "chunk"
                )

                if chunk is None:
                    continue

                content = getattr(
                    chunk,
                    "content",
                    "",
                )

                if isinstance(
                    content,
                    list,
                ):

                    text_parts = []

                    for item in content:

                        if not isinstance(
                            item,
                            dict,
                        ):
                            continue

                        text = item.get(
                            "text",
                            "",
                        )

                        if text:
                            text_parts.append(
                                text
                            )

                    content = "".join(
                        text_parts
                    )

                if content:

                    yield {
                        "type": "token",
                        "content": content,
                    }

                usage_metadata = getattr(
                    chunk,
                    "usage_metadata",
                    None
                )

                if usage_metadata:

                    input_tokens += int(
                        usage_metadata.get(
                            "input_tokens",
                            0,
                        )
                        or 0
                    )

                    output_tokens += int(
                        usage_metadata.get(
                            "output_tokens",
                            0,
                        )
                        or 0
                    )

            elif event_type == "on_tool_end":

                output = event.get(
                    "data",
                    {},
                ).get(
                    "output"
                )

                if output is None:
                    continue

                content = getattr(
                    output,
                    "content",
                    output,
                )

                if isinstance(
                    content,
                    str,
                ):

                    try:
                        content = json.loads(
                            content
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):
                        continue

                if not isinstance(
                    content,
                    dict,
                ):
                    continue
                
                if "sql" not in content:
                    continue

                sql = content.get(
                    "sql"
                )

                used_columns = content.get(
                    "used_columns",
                    [],
                )

                data = {
                    "dataset_id": dataset_id,
                    "columns": content.get(
                        "columns",
                        [],
                    ),
                    "rows": content.get(
                        "rows",
                        [],
                    ),
                    "row_count": content.get(
                        "row_count",
                        0,
                    ),
                }

                if not metadata_sent:

                    metadata_sent = True

                    yield {
                        "type": "metadata",
                        "used_columns": used_columns,
                        "sql": sql,
                        "data": data,
                    }

        total_tokens = (
            input_tokens
            + output_tokens
        )

        cost = self.calculate_cost(
            model=model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
        )

        yield {
            "type": "done",
            "usage": {
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "total_tokens": total_tokens,
            },
            "cost": cost,
        }
